runtime: python38
service: "russel3000-v03"
env: standard
instance_class: F4_1G
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: polished-vault-379315@appspot.gserviceaccount.com