runtime: python38
service: "russel3000-v03"
env: standard
instance_class: F4
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: valid-heuristic-369117@appspot.gserviceaccount.com